# Generated by Django 4.2.10 on 2024-02-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_country_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookImage', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
